# .streamlit/secrets.toml

[google]
type = "service_account"
project_id = "comercial-447112"
private_key_id = "6d38210fe4b84524cb1a238c5a7d9f248dea9cf3"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDSuoS95eDtjESB
KNL6WFAOCatUeeb0IfKTTNyrAMMXBAvlg5C1X/ylUlffIXBWWsTlcX7usfxMupCv
...
WSGa2e5
-----END PRIVATE KEY-----"""
client_email = "extra-o-comercial@comercial-447112.iam.gserviceaccount.com"
client_id = "112170784520261428010"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/extra-o-comercial%40comercial-447112.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
